spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
      - id: hobby-service
        uri: lb://hobby-service
        predicatgites:
        - Path=/hobby/**
      - id: course-service
        uri: lb://course-service
        predicates:
        - Path=/course/**
      - id: info-service
        uri: lb://info-service
        predicates:
        - Path=/info/**
      - id: microservice
        uri: lb://microservice
        predicates:
        - Path=/**
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
